export const presets: [string, string][] = [
  ['Anaheim', '?MLB_LAA=Red&NHL_ANA=Orange'],
  ['Atlanta', '?MLB_ATL=Navy&NBA_ATL=Red&NFL_ATL=Black'],
  ['Baltimore', '?MLB_BAL=Orange&NFL_BAL=Purple'],
  ['Boston', '?MLB_BOS=Red&NBA_BOS=Green&NFL_NE=Navy&NHL_BOS=Yellow'],
  ['Buffalo', '?NFL_BUF=Royal&NHL_BUF=Yellow'],
  ['Chicago', '?MLB_CHC=Royal&MLB_CHW=Silver&NBA_CHI=Black&NFL_CHI=Orange&NHL_CHI=Red'],
  ['Cincinnati', '?MLB_CIN=Red&NFL_CIN=Orange'],
  ['Cleveland', '?MLB_CLE=Navy&NBA_CLE=Brick&NFL_CLE=Orange'],
  ['Dallas-Fort Worth', '?MLB_TEX=Red&NBA_DAL=Royal&NFL_DAL=Navy&NHL_DAL=Green'],
  ['Denver', '?MLB_COL=Purple&NBA_DEN=Sky&NFL_DEN=Orange&NHL_COL=Brick'],
  ['Detroit', '?MLB_DET=Orange&NBA_DET=Royal&NFL_DET=Silver&NHL_DET=Red'],
  ['Houston', '?MLB_HOU=Orange&NBA_HOU=Red&NFL_HOU=Navy'],
  ['Indianapolis', '?NBA_IND=Yellow&NFL_IND=Royal'],
  ['Kansas City', '?MLB_KC=Royal&NFL_KC=Red'],
  ['Las Vegas', '?NFL_LV=Black&NHL_VGS=Gold'],
  ['Los Angeles', '?MLB_LAD=Royal&NBA_LAC=Red&NBA_LAL=Purple&NFL_LAC=Sky&NFL_LAR=Yellow&NHL_LA=Black'],
  ['Miami', '?MLB_MIA=Black&NBA_MIA=Pink&NFL_MIA=Teal&NHL_FLA=Red'],
  ['Minneapolis-Saint Paul', '?MLB_MIN=Red&NBA_MIN=Navy&NFL_MIN=Purple&NHL_MIN=Green'],
  ['New Orleans', '?NBA_NO=Navy&NFL_NO=Gold'],
  [
    'New York',
    '?MLB_NYM=Pink&MLB_NYY=Navy&NBA_BKN=Black&NBA_NY=Orange&NFL_NYG=Silver&NFL_NYJ=Green&NHL_NJ=Red&NHL_NYI=Teal&NHL_NYR=Royal',
  ],
  ['North Carolina', '?NBA_CHA=Purple&NFL_CAR=Sky&NHL_CAR=Red'],
  ['Philadelphia', '?MLB_PHI=Red&NBA_PHI=Royal&NFL_PHI=Teal&NHL_PHI=Orange'],
  ['Phoenix', '?MLB_ARI=Brick&NBA_PHX=Purple&NFL_ARI=Red&NHL_ARI=Black'],
  ['Pittsburgh', '?MLB_PIT=Yellow&NFL_PIT=Black&NHL_PIT=Sky'],
  ['San Francisco Bay Area', '?MLB_OAK=Green&MLB_SF=Orange&NBA_GS=Royal&NFL_SF=Red&NHL_SJ=Teal'],
  ['Seattle', '?MLB_SEA=Teal&NFL_SEA=Navy'],
  ['St. Louis', '?MLB_STL=Red&NHL_STL=Royal'],
  ['Tampa Bay', '?MLB_TB=Sky&NFL_TB=Red&NHL_TB=Royal'],
  ['Tennessee', '?NBA_MEM=Sky&NFL_TEN=Navy&NHL_NSH=Yellow'],
  ['Toronto', '?MLB_TOR=Royal&NBA_TOR=Red&NHL_TOR=Navy'],
  ['Washington', '?MLB_WSH=Navy&NBA_WSH=Silver&NFL_WSH=Brick&NHL_WSH=Red'],
  ['Wisconsin', '?MLB_MIL=Navy&NBA_MIL=Purple&NFL_GB=Green'],
];
