export enum Colour {
  RED,
  BRICK,
  ORANGE,
  YELLOW,
  GOLD,
  GREEN,
  TEAL,
  SKY,
  ROYAL,
  NAVY,
  PURPLE,
  PINK,
  BROWN,
  BLACK,
  SILVER,
  GREY,
}

export enum MLB {
  ARI,
  ATL,
  BAL,
  BOS,
  CHC,
  CIN,
  CLE,
  COL,
  CWS,
  DET,
  HOU,
  KC,
  LAA,
  LAD,
  MIA,
  MIL,
  MIN,
  NYM,
  NYY,
  OAK,
  PHI,
  PIT,
  SD,
  SEA,
  SF,
  STL,
  TB,
  TEX,
  TOR,
  WSH,
}

export enum NBA {
  ATL,
  BKN,
  BOS,
  CHA,
  CHI,
  CLE,
  DAL,
  DEN,
  DET,
  GS,
  HOU,
  IND,
  LAC,
  LAL,
  MEM,
  MIA,
  MIL,
  MIN,
  NO,
  NY,
  OKC,
  ORL,
  PHI,
  PHX,
  POR,
  SA,
  SAC,
  TOR,
  UTA,
  WSH,
}

export enum NFL {
  ARI,
  ATL,
  BAL,
  BUF,
  CAR,
  CHI,
  CIN,
  CLE,
  DAL,
  DEN,
  DET,
  GB,
  HOU,
  IND,
  JAX,
  KC,
  LAC,
  LAR,
  LV,
  MIA,
  MIN,
  NE,
  NO,
  NYG,
  NYJ,
  PHI,
  PIT,
  SEA,
  SF,
  TB,
  TEN,
  WSH,
}

export enum NHL {
  ANA,
  ARI,
  BOS,
  BUF,
  CAR,
  CBJ,
  CGY,
  CHI,
  COL,
  DAL,
  DET,
  EDM,
  FLA,
  LA,
  MIN,
  MTL,
  NJ,
  NSH,
  NYI,
  NYR,
  OTT,
  PHI,
  PIT,
  SJ,
  STL,
  TB,
  TOR,
  VAN,
  VGK,
  WPG,
  WSH,
}

export type Team = MLB | NBA | NFL | NHL;

export const TEAM_NAMES = new Map<Team, string>([
  [MLB.ARI, 'Arizona Diamondbacks'],
  [MLB.ATL, 'Atlanta Braves'],
  [MLB.BAL, 'Baltimore Orioles'],
  [MLB.BOS, 'Boston Red Sox'],
  [MLB.CHC, 'Chicago Cubs'],
  [MLB.CIN, 'Cincinnati Reds'],
  [MLB.CLE, 'Cleveland Baseball Team'],
  [MLB.COL, 'Colorado Rockies'],
  [MLB.CWS, 'Chicago White Sox'],
  [MLB.DET, 'Detroit Tigers'],
  [MLB.HOU, 'Houston Astros'],
  [MLB.KC, 'Kansas City Royals'],
  [MLB.LAA, 'Los Angeles Angels'],
  [MLB.LAD, 'Los Angeles Dodgers'],
  [MLB.MIA, 'Miami Marlins'],
  [MLB.MIL, 'Milwaukee Brewers'],
  [MLB.MIN, 'Minnesota Twins'],
  [MLB.NYM, 'New York Mets'],
  [MLB.NYY, 'New York Yankees'],
  [MLB.OAK, "Oakland A's"],
  [MLB.PHI, 'Philadelphia Phillies'],
  [MLB.PIT, 'Pittsburgh Pirates'],
  [MLB.SD, 'San Diego Padres'],
  [MLB.SEA, 'Seattle Mariners'],
  [MLB.SF, 'San Francisco Giants'],
  [MLB.STL, 'St. Louis Cardinals'],
  [MLB.TB, 'Tampa Bay Rays'],
  [MLB.TEX, 'Texas Rangers'],
  [MLB.TOR, 'Toronto Blue Jays'],
  [MLB.WSH, 'Washington Nationals'],
  [NBA.ATL, 'Atlanta Hawks'],
  [NBA.BKN, 'Brooklyn Nets'],
  [NBA.BOS, 'Boston Celtics'],
  [NBA.CHA, 'Charlotte Hornets'],
  [NBA.CHI, 'Chicago Bulls'],
  [NBA.CLE, 'Cleveland Cavaliers'],
  [NBA.DAL, 'Dallas Mavericks'],
  [NBA.DEN, 'Denver Nuggets'],
  [NBA.DET, 'Detroit Pistons'],
  [NBA.GS, 'Golden State Warriors'],
  [NBA.HOU, 'Houston Rockets'],
  [NBA.IND, 'Indiana Pacers'],
  [NBA.LAC, 'Los Angeles Clippers'],
  [NBA.LAL, 'Los Angeles Lakers'],
  [NBA.MEM, 'Memphis Grizzlies'],
  [NBA.MIA, 'Miami Heat'],
  [NBA.MIL, 'Milwaukee Bucks'],
  [NBA.MIN, 'Minnesota Timberwolves'],
  [NBA.NO, 'New Orleans Pelicans'],
  [NBA.NY, 'New York Knicks'],
  [NBA.OKC, 'Oklahoma City Thunder'],
  [NBA.ORL, 'Orlando Magic'],
  [NBA.PHI, 'Philadelphia 76ers'],
  [NBA.PHX, 'Phoenix Suns'],
  [NBA.POR, 'Portland Trail Blazers'],
  [NBA.SA, 'San Antonio Spurs'],
  [NBA.SAC, 'Sacramento Kings'],
  [NBA.TOR, 'Toronto Raptors'],
  [NBA.UTA, 'Utah Jazz'],
  [NBA.WSH, 'Washington Wizards'],
  [NFL.ARI, 'Arizona Cardinals'],
  [NFL.ATL, 'Atlanta Falcons'],
  [NFL.BAL, 'Baltimore Ravens'],
  [NFL.BUF, 'Buffalo Bills'],
  [NFL.CAR, 'Carolina Panthers'],
  [NFL.CHI, 'Chicago Bears'],
  [NFL.CIN, 'Cincinnati Bengals'],
  [NFL.CLE, 'Cleveland Browns'],
  [NFL.DAL, 'Dallas Cowboys'],
  [NFL.DEN, 'Denver Broncos'],
  [NFL.DET, 'Detroit Lions'],
  [NFL.GB, 'Green Bay Packers'],
  [NFL.HOU, 'Houston Texans'],
  [NFL.IND, 'Indianapolis Colts'],
  [NFL.JAX, 'Jacksonville Jaguars'],
  [NFL.KC, 'Kansas City Chiefs'],
  [NFL.LAC, 'Los Angeles Chargers'],
  [NFL.LAR, 'Los Angeles Rams'],
  [NFL.LV, 'Las Vegas Raiders'],
  [NFL.MIA, 'Miami Dolphins'],
  [NFL.MIN, 'Minnesota Vikings'],
  [NFL.NE, 'New England Patriots'],
  [NFL.NO, 'New Orleans Saints'],
  [NFL.NYG, 'New York Giants'],
  [NFL.NYJ, 'New York Jets'],
  [NFL.PHI, 'Philadelphia Eagles'],
  [NFL.PIT, 'Pittsburgh Steelers'],
  [NFL.SEA, 'Seattle Seahawks'],
  [NFL.SF, 'San Francisco 49ers'],
  [NFL.TB, 'Tampa Bay Buccaneers'],
  [NFL.TEN, 'Tennessee Titans'],
  [NFL.WSH, 'Washington Football Team'],
  [NHL.ANA, 'Anaheim Ducks'],
  [NHL.ARI, 'Arizona Coyotes'],
  [NHL.BOS, 'Boston Bruins'],
  [NHL.BUF, 'Buffalo Sabres'],
  [NHL.CAR, 'Carolina Hurricanes'],
  [NHL.CBJ, 'Columbus Blue Jackets'],
  [NHL.CGY, 'Calgary Flames'],
  [NHL.CHI, 'Chicago Blackhawks'],
  [NHL.COL, 'Colorado Avalanche'],
  [NHL.DAL, 'Dallas Stars'],
  [NHL.DET, 'Detroit Red Wings'],
  [NHL.EDM, 'Edmonton Oilers'],
  [NHL.FLA, 'Florida Panthers'],
  [NHL.LA, 'Los Angeles Kings'],
  [NHL.MIN, 'Minnesota Wild'],
  [NHL.MTL, 'Montreal Canadiens'],
  [NHL.NJ, 'New Jersey Devils'],
  [NHL.NSH, 'Nashville Predators'],
  [NHL.NYI, 'New York Islanders'],
  [NHL.NYR, 'New York Rangers'],
  [NHL.OTT, 'Ottawa Senators'],
  [NHL.PHI, 'Philadelphia Flyers'],
  [NHL.PIT, 'Pittsburgh Penguins'],
  [NHL.SJ, 'San Jose Sharks'],
  [NHL.STL, 'St. Louis Blues'],
  [NHL.TB, 'Tampa Bay Lightning'],
  [NHL.TOR, 'Toronto Maple Leafs'],
  [NHL.VAN, 'Vancouver Canucks'],
  [NHL.VGK, 'Vegas Golden Knights'],
  [NHL.WPG, 'Winnipeg Jets'],
  [NHL.WSH, 'Washington Capitals'],
]);

export const TEAM_COLOURS = new Map<Team, Colour[]>([
  [NHL.ANA, [Colour.ORANGE, Colour.GOLD, Colour.BLACK, Colour.PURPLE, Colour.TEAL]],
  [NHL.ARI, [Colour.BRICK, Colour.BLACK, Colour.GREEN, Colour.PURPLE, Colour.ORANGE, Colour.RED]],
  [NHL.BOS, [Colour.YELLOW, Colour.BLACK, Colour.BROWN, Colour.GOLD]],
  [NHL.BUF, [Colour.ROYAL, Colour.YELLOW, Colour.NAVY, Colour.SILVER, Colour.GOLD, Colour.BLACK, Colour.RED]],
  [
    NHL.CAR,
    [Colour.RED, Colour.BLACK, Colour.SILVER, Colour.GREY, Colour.GREEN, Colour.NAVY, Colour.ROYAL, Colour.BRICK],
  ],
  [NHL.CBJ, [Colour.NAVY, Colour.RED, Colour.SILVER, Colour.YELLOW]],
  [NHL.CGY, [Colour.RED, Colour.YELLOW, Colour.BLACK, Colour.BRICK]],
  [NHL.CHI, [Colour.RED, Colour.BLACK, Colour.YELLOW, Colour.ORANGE, Colour.GREEN]],
  [
    NHL.COL,
    [Colour.BRICK, Colour.SKY, Colour.NAVY, Colour.SILVER, Colour.ROYAL, Colour.BLACK, Colour.RED, Colour.YELLOW],
  ],
  [NHL.DAL, [Colour.GREEN, Colour.BLACK, Colour.SILVER, Colour.GOLD, Colour.YELLOW]],
  [NHL.DET, [Colour.RED, Colour.PURPLE, Colour.SILVER, Colour.GREY, Colour.BLACK]],
  [NHL.EDM, [Colour.ORANGE, Colour.ROYAL, Colour.NAVY, Colour.SILVER, Colour.GREY]],
  [NHL.FLA, [Colour.RED, Colour.NAVY, Colour.GOLD, Colour.YELLOW, Colour.BRICK]],
  [NHL.LA, [Colour.BLACK, Colour.SILVER, Colour.PURPLE, Colour.YELLOW, Colour.GREY]],
  [NHL.MIN, [Colour.GREEN, Colour.BRICK, Colour.RED, Colour.YELLOW]],
  [NHL.MTL, [Colour.RED, Colour.ROYAL, Colour.NAVY]],
  [NHL.NJ, [Colour.RED, Colour.BLACK, Colour.GREEN]],
  [NHL.NSH, [Colour.YELLOW, Colour.NAVY, Colour.SILVER, Colour.ROYAL]],
  [NHL.NYI, [Colour.ROYAL, Colour.ORANGE, Colour.NAVY, Colour.TEAL, Colour.BLACK]],
  [NHL.NYR, [Colour.ROYAL, Colour.RED, Colour.NAVY, Colour.SILVER]],
  [NHL.OTT, [Colour.RED, Colour.BLACK, Colour.GOLD, Colour.BRICK, Colour.YELLOW]],
  [NHL.PHI, [Colour.ORANGE, Colour.BLACK]],
  [NHL.PIT, [Colour.YELLOW, Colour.BLACK, Colour.GOLD, Colour.SKY, Colour.NAVY, Colour.ROYAL, Colour.GREY]],
  [NHL.SJ, [Colour.TEAL, Colour.BLACK, Colour.SILVER, Colour.ORANGE, Colour.GREY]],
  [NHL.STL, [Colour.ROYAL, Colour.NAVY, Colour.YELLOW, Colour.RED, Colour.BRICK]],
  [NHL.TB, [Colour.ROYAL, Colour.SILVER, Colour.BLACK, Colour.GREY]],
  [NHL.TOR, [Colour.ROYAL, Colour.NAVY, Colour.GREEN, Colour.SILVER]],
  [
    NHL.VAN,
    [
      Colour.ROYAL,
      Colour.NAVY,
      Colour.GREEN,
      Colour.BRICK,
      Colour.YELLOW,
      Colour.RED,
      Colour.BLACK,
      Colour.ORANGE,
      Colour.SILVER,
    ],
  ],
  [NHL.VGK, [Colour.GOLD, Colour.GREY, Colour.BLACK, Colour.YELLOW, Colour.RED, Colour.SILVER]],
  [NHL.WPG, [Colour.NAVY, Colour.SKY, Colour.GREY, Colour.SILVER, Colour.ROYAL, Colour.RED]],
  [NHL.WSH, [Colour.RED, Colour.NAVY, Colour.ROYAL, Colour.GOLD, Colour.BLACK]],
  [MLB.ARI, [Colour.BRICK, Colour.BLACK, Colour.PURPLE, Colour.TEAL, Colour.RED]],
  [MLB.ATL, [Colour.NAVY, Colour.RED, Colour.ROYAL, Colour.SKY, Colour.YELLOW]],
  [MLB.BAL, [Colour.ORANGE, Colour.BLACK]],
  [MLB.BOS, [Colour.RED, Colour.NAVY, Colour.GREEN]],
  [MLB.CHC, [Colour.ROYAL, Colour.RED, Colour.NAVY, Colour.SKY, Colour.BRICK]],
  [MLB.CIN, [Colour.RED, Colour.BRICK, Colour.BLACK, Colour.NAVY]],
  [MLB.CLE, [Colour.NAVY, Colour.RED]],
  [MLB.COL, [Colour.PURPLE, Colour.SILVER, Colour.BLACK]],
  [MLB.CWS, [Colour.BLACK, Colour.SILVER, Colour.RED]],
  [MLB.DET, [Colour.NAVY, Colour.ORANGE, Colour.GREY]],
  [MLB.HOU, [Colour.ORANGE, Colour.NAVY, Colour.ROYAL]],
  [MLB.KC, [Colour.ROYAL, Colour.GOLD, Colour.SKY]],
  [MLB.LAA, [Colour.RED, Colour.NAVY, Colour.SKY, Colour.YELLOW]],
  [MLB.LAD, [Colour.ROYAL, Colour.SKY, Colour.RED, Colour.NAVY]],
  [MLB.MIA, [Colour.BLACK, Colour.SKY, Colour.TEAL, Colour.ORANGE, Colour.PINK, Colour.RED, Colour.YELLOW]],
  [MLB.MIL, [Colour.NAVY, Colour.YELLOW, Colour.ROYAL, Colour.GOLD, Colour.GREEN]],
  [MLB.MIN, [Colour.NAVY, Colour.RED, Colour.GOLD, Colour.SKY]],
  [MLB.NYM, [Colour.ROYAL, Colour.ORANGE, Colour.BLACK, Colour.PINK]],
  [MLB.NYY, [Colour.NAVY, Colour.SILVER, Colour.GREY]],
  [MLB.OAK, [Colour.GREEN, Colour.YELLOW]],
  [MLB.PHI, [Colour.RED, Colour.ROYAL, Colour.BRICK, Colour.SKY]],
  [MLB.PIT, [Colour.YELLOW, Colour.BLACK, Colour.RED, Colour.GOLD]],
  [MLB.SD, [Colour.BROWN, Colour.YELLOW, Colour.ORANGE, Colour.NAVY, Colour.SKY]],
  [MLB.SEA, [Colour.TEAL, Colour.NAVY, Colour.ROYAL, Colour.YELLOW, Colour.GREY]],
  [MLB.SF, [Colour.ORANGE, Colour.BLACK, Colour.GOLD]],
  [MLB.STL, [Colour.RED, Colour.NAVY, Colour.YELLOW, Colour.SKY]],
  [MLB.TB, [Colour.SKY, Colour.NAVY, Colour.PURPLE, Colour.GREEN, Colour.YELLOW, Colour.BLACK]],
  [MLB.TEX, [Colour.ROYAL, Colour.RED, Colour.SKY]],
  [MLB.TOR, [Colour.ROYAL, Colour.NAVY, Colour.SKY, Colour.RED, Colour.GREY]],
  [MLB.WSH, [Colour.NAVY, Colour.RED, Colour.SILVER, Colour.GREY]],
  [NBA.ATL, [Colour.RED, Colour.BLACK, Colour.YELLOW, Colour.NAVY, Colour.SILVER, Colour.ROYAL, Colour.GREEN]],
  [NBA.BKN, [Colour.BLACK, Colour.SILVER, Colour.GREY, Colour.SKY, Colour.NAVY, Colour.RED, Colour.ROYAL]],
  [NBA.BOS, [Colour.GREEN, Colour.GOLD, Colour.YELLOW, Colour.ORANGE]],
  [NBA.CHA, [Colour.TEAL, Colour.PURPLE]],
  [NBA.CHI, [Colour.RED, Colour.BLACK, Colour.SILVER]],
  [NBA.CLE, [Colour.BRICK, Colour.YELLOW, Colour.NAVY, Colour.GOLD, Colour.ORANGE, Colour.SKY, Colour.RED]],
  [NBA.DAL, [Colour.ROYAL, Colour.NAVY, Colour.SILVER, Colour.GREY, Colour.BLACK, Colour.GREEN]],
  [NBA.DEN, [Colour.NAVY, Colour.BRICK, Colour.YELLOW, Colour.SKY]],
  [NBA.DET, [Colour.ROYAL, Colour.RED, Colour.TEAL, Colour.BLACK]],
  [NBA.GS, [Colour.ROYAL, Colour.YELLOW, Colour.NAVY, Colour.ORANGE, Colour.SKY, Colour.GOLD]],
  [NBA.HOU, [Colour.RED, Colour.BLACK, Colour.GREY, Colour.SILVER, Colour.YELLOW]],
  [NBA.IND, [Colour.NAVY, Colour.YELLOW, Colour.ROYAL]],
  [NBA.LAC, [Colour.RED, Colour.ROYAL, Colour.BLACK, Colour.SKY, Colour.ORANGE]],
  [NBA.LAL, [Colour.PURPLE, Colour.YELLOW, Colour.BLACK, Colour.SKY, Colour.ROYAL]],
  [NBA.MEM, [Colour.SKY, Colour.NAVY, Colour.YELLOW, Colour.TEAL, Colour.BLACK, Colour.RED, Colour.BROWN]],
  [NBA.MIA, [Colour.RED, Colour.BLACK, Colour.PINK, Colour.SKY, Colour.YELLOW, Colour.ORANGE, Colour.BRICK]],
  [NBA.MIL, [Colour.GREEN, Colour.BROWN, Colour.RED, Colour.PURPLE]],
  [NBA.MIN, [Colour.ROYAL, Colour.NAVY, Colour.SILVER, Colour.GREEN, Colour.GREY, Colour.BLACK]],
  [NBA.NO, [Colour.NAVY, Colour.GOLD, Colour.RED, Colour.BRICK, Colour.PURPLE, Colour.GREEN, Colour.YELLOW]],
  [NBA.NY, [Colour.ROYAL, Colour.ORANGE, Colour.BLACK]],
  [NBA.OKC, [Colour.SKY, Colour.ORANGE, Colour.YELLOW, Colour.NAVY, Colour.ROYAL]],
  [NBA.ORL, [Colour.BLACK, Colour.ROYAL, Colour.SILVER, Colour.ORANGE]],
  [NBA.PHI, [Colour.ROYAL, Colour.RED, Colour.BLACK, Colour.GOLD]],
  [NBA.PHX, [Colour.PURPLE, Colour.ORANGE, Colour.YELLOW, Colour.BLACK]],
  [NBA.POR, [Colour.BLACK, Colour.RED, Colour.SILVER, Colour.GREY]],
  [NBA.SAC, [Colour.PURPLE, Colour.SILVER, Colour.BLACK, Colour.GREY, Colour.SKY, Colour.RED]],
  [NBA.SA, [Colour.BLACK, Colour.SILVER, Colour.TEAL, Colour.PINK, Colour.ORANGE]],
  [NBA.TOR, [Colour.RED, Colour.PURPLE, Colour.BLACK, Colour.GOLD]],
  [
    NBA.UTA,
    [Colour.NAVY, Colour.YELLOW, Colour.GREEN, Colour.PURPLE, Colour.SKY, Colour.ORANGE, Colour.RED, Colour.BRICK],
  ],
  [NBA.WSH, [Colour.NAVY, Colour.RED, Colour.SILVER, Colour.GOLD, Colour.ROYAL, Colour.BLACK]],
  [NFL.ARI, [Colour.RED, Colour.BRICK, Colour.BLACK, Colour.YELLOW, Colour.GREY]],
  [NFL.ATL, [Colour.BLACK, Colour.RED, Colour.BRICK, Colour.SILVER, Colour.GREY]],
  [NFL.BAL, [Colour.PURPLE, Colour.BLACK, Colour.GOLD, Colour.YELLOW, Colour.RED]],
  [NFL.BUF, [Colour.ROYAL, Colour.RED]],
  [NFL.CAR, [Colour.SKY, Colour.BLACK, Colour.SILVER]],
  [NFL.CHI, [Colour.NAVY, Colour.ORANGE]],
  [NFL.CIN, [Colour.ORANGE, Colour.BLACK]],
  [NFL.CLE, [Colour.BROWN, Colour.ORANGE]],
  [NFL.DAL, [Colour.NAVY, Colour.SILVER, Colour.ROYAL]],
  [NFL.DEN, [Colour.NAVY, Colour.ORANGE, Colour.BROWN, Colour.YELLOW, Colour.ROYAL]],
  [NFL.DET, [Colour.SKY, Colour.SILVER, Colour.ROYAL, Colour.BLACK]],
  [NFL.GB, [Colour.GREEN, Colour.YELLOW, Colour.NAVY]],
  [NFL.HOU, [Colour.NAVY, Colour.RED, Colour.SKY]],
  [NFL.IND, [Colour.ROYAL, Colour.NAVY, Colour.BLACK]],
  [NFL.JAX, [Colour.TEAL, Colour.GOLD, Colour.BLACK, Colour.YELLOW]],
  [NFL.KC, [Colour.RED, Colour.YELLOW]],
  [NFL.LAC, [Colour.SKY, Colour.YELLOW, Colour.NAVY, Colour.ROYAL]],
  [NFL.LAR, [Colour.ROYAL, Colour.YELLOW, Colour.NAVY, Colour.GOLD]],
  [NFL.LV, [Colour.BLACK, Colour.SILVER]],
  [NFL.MIA, [Colour.TEAL, Colour.ORANGE]],
  [NFL.MIN, [Colour.PURPLE, Colour.YELLOW]],
  [NFL.NE, [Colour.NAVY, Colour.SILVER, Colour.RED, Colour.ROYAL]],
  [NFL.NO, [Colour.GOLD, Colour.BLACK]],
  [NFL.NYG, [Colour.NAVY, Colour.RED, Colour.ROYAL]],
  [NFL.NYJ, [Colour.GREEN, Colour.BLACK]],
  [NFL.PHI, [Colour.TEAL, Colour.GREEN, Colour.SILVER, Colour.BLACK]],
  [NFL.PIT, [Colour.YELLOW, Colour.BLACK, Colour.SILVER]],
  [NFL.SEA, [Colour.NAVY, Colour.SILVER, Colour.GREEN, Colour.ROYAL]],
  [NFL.SF, [Colour.RED, Colour.GOLD, Colour.BRICK, Colour.BLACK]],
  [NFL.TB, [Colour.RED, Colour.ORANGE, Colour.GREY, Colour.BLACK, Colour.BROWN]],
  [NFL.TEN, [Colour.SKY, Colour.NAVY, Colour.RED, Colour.SILVER]],
  [NFL.WSH, [Colour.BRICK, Colour.YELLOW, Colour.GOLD, Colour.BROWN]],
]);
